[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bookarm_control_py"
version = "0.1.0"
description = "Python control package for the book arm robot."
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "beiyu" }
]
dependencies = [
    "numpy>=2.4.3",
    "pin >= 4.0.0",
    "pyserial>=3.5",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
